### ISSUE TITLE
RuntimeError: The shape of the mask [230202] at index 0 does not match the shape of the indexed tensor [0] at index 0

### ISSUE THREAD

**Issue by liminghao1630** [facebookresearch/maskrcnn-benchmark#31] opened 2018-10-26 09:07 UTC
## ❓ Questions and Help
Traceback (most recent call last):
  File "github/maskrcnn-benchmark/tools/train_net.py", line 170, in <module>
    main()
  File "github/maskrcnn-benchmark/tools/train_net.py", line 163, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "github/maskrcnn-benchmark/tools/train_net.py", line 73, in train
    arguments,
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 65, in do_train
    loss_dict = model(images, targets)
  File "/home/v-minghl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/v-minghl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 94, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets)
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 113, in _forward_train
    anchors, objectness, rpn_box_regression, targets
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/loss.py", line 91, in __call__
    labels, regression_targets = self.prepare_targets(anchors, targets)
  File "/home/v-minghl/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/loss.py", line 62, in prepare_targets
    labels_per_image[~anchors_per_image.get_field("visibility")] = -1
RuntimeError: The shape of the mask [230202] at index 0 does not match the shape of the indexed tensor [0] at index 0

Hi,
I used my own data set in coco format to train.   batchsize 2 and max iter is 15000.   Train on P100 * 1.
It can succeed to run for 2540 iters and crashed with this error.
I succeed to train this data set with mmdetection. 
I have no idea why the error happened, please give me some help.

**Comment by fmassa** [comment] 2018-10-26 09:12
Hi,

This error usually happens when the learning rate is too high: the gradients explode, and the activations become inf, so that once we try to perform indexing it gets out of range.

That would be my first guess, but let me see in a bit more detail to see if it could be something else

**Comment by fmassa** [comment] 2018-10-26 09:17
I actually think that this error might come from a different place.

I have the impression that one of your images doesn't have a bounding box target. Is that right?

**Comment by fmassa** [comment] 2018-10-26 09:54
I have been looking into mmdetection implementation, and they raise an error if there are no ground-truth boxes in the image, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assignment.py#L92-L93).
Could you verify that there is indeed at least one image where there are no ground-truth boxes?
I should probably add an error as well, instead of silently returning an empty tensor.

**Comment by mveres01** [comment] 2018-10-26 15:31
I had a similar error this that was caused by a segmentation started for an image but never finished (e.g. ```ann['segmentation'] = []```). This doesn't get caught by https://github.com/facebookresearch/maskrcnn-benchmark/issues/31#issuecomment-433345407

A dirty workaround is something like:

```
if remove_images_without_annotations: 
    ...

out = []
for id in self.ids:
    ann_ids = self.coco.getAnnIds(imgIds=id)

    for ann in self.coco.loadAnns(ann_ids):
        if len(ann['segmentation']) > 0:
            out.append(id)
            break

self.ids = out
```

**Comment by liminghao1630** [comment] 2018-10-26 15:59
When I change the code as what you mentioned at #37 , the error get caught by "ValueError: No ground-truth boxes available for one of the images".    Sorry for that, I think it may because I check my data set in pascal voc format but the code changing format from pascal voc to coco had some problem.    Is it possible when the error was caught to print the filename of image?

**Comment by fmassa** [comment] 2018-10-26 16:05
I think it is possible to do so, but we would need to do it in the dataset class itself, somewhere near here https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/coco.py#L40
Something like
```
if not anno:
    raise ValueError("Image id {} ({}) doesn't have annotations!".format(self.ids[idx], anno))
```

Let me know what happens. I'm looking into improving the error message for those corner cases.

**Comment by liminghao1630** [comment] 2018-10-27 03:09
@fmassa  Hi
I have changed the code. But it was only caught by this error "ValueError: No ground-truth boxes available for one of the images".
By the way, when I use mmdetection and tensorflow OD API(faster rcnn), I can use batchsize 8 to train. When I use maskrcnn-benchmark(mask rcnn) I can only use batchsize 2. If changed bigger, for example batchsize 4, it will crash with "RuntimeError: CUDA error: out of memory".
I noticed the config file have no information about the resizer.  So I guess maybe it was due to this?
`MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  MASK_ON: True
DATASETS:
  TRAIN: ("latex_5000", "latex_5000")
  TEST: ("latex_5000",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (10000, 12000)
  MAX_ITER: 15000
  IMS_PER_BATCH: 2
`

**Comment by fmassa** [comment] 2018-10-27 15:44
I had modified the initial message that I sent, check it again, there was a bug in the initial version that I posted and now it should show the image that is problematic. The new version is edited in GitHub in this thread

**Comment by zylhub** [comment] 2018-10-30 02:45
I got the same issue too.  When I check the data, I find that there is an empty box .

> so, I ignored these data when training. untile now, everything is fine.

And here is what I modified  https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/engine/trainer.py#L57
```python
  for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
        data_time = time.time() - end
        arguments["iteration"] = iteration
        # add ignore 
        if len(targets[0]) < 1:
            print('num_boxes: ', len(targets[0]))
            continue
        scheduler.step()


```

**Comment by fmassa** [comment] 2018-10-30 07:49
@zylhub thanks for the snippet!
My original idea was to make the dataset remove the empty boxes when in training mode, but it seems that my solution is not adapted to all cases.
Just to know, did you write your own dataset class, or are you using the COCODataset, and feeding your data in COCO format?

**Comment by zylhub** [comment] 2018-10-31 03:13
@fmassa  yes, I have write my own dataset class, and feeding in coco formats.

**Comment by fmassa** [comment] 2018-10-31 08:56
My assumption in this case was that the code I wrote in the `__init__` of the COCODataset class would remove images with empty boxes.

I still need to understand why this isn't the case, So that I can make the code more robust. Skipping the batch is definitely a solution, but I'd rather avoid it for now

**Comment by xuanyuzhou98** [comment] 2018-11-01 17:33
@fmassa I think the code at __init__ is not enough to prevent that error. We also need a check after calling "clip_to_image" at __getitem__ to further prevent empty bounding box.

**Comment by fmassa** [comment] 2018-11-01 23:57
@xuanyuzhou98 oh, that a very good point!
I'll add a check in the dataset loading as well, thanks!

**Comment by liminghao1630** [comment] 2018-11-02 02:53
@fmassa Hi, I found the reason which may cause the strange phenomenon! 
I used the data for object detection directly in maskrcnn without segment annotations.

**Comment by fmassa** [comment] 2018-11-02 09:12
@liminghao1630 thanks for reaching back. Could you explain a bit more what was happening before, and maybe how we could the asserts more robust?

**Comment by jonasteuwen** [comment] 2018-11-02 23:00
I get a similar problem. However, I converted my dataset to mscoco, and I have both bbox and segmentations, but not all images have segmentations in which case I only use bbox'es. As a first try, I decided to run FasterRCNN (MODEL.MASK_ON = False), and in that case set in `coco.py` this to false:
```
        masks = [obj["segmentation"] for obj in anno]
        masks = SegmentationMask(masks, img.size)
        target.add_field("masks", masks)
```
Should that be sufficient? In any case, running FasterRCNN shouldn't need the segmentations.

**Comment by miguelvr** [comment] 2018-12-14 13:58
This was happening to me because some of my annotations were out of image bounds. Maybe it is worth it to have a check against this.

**Comment by miguelvr** [comment] 2018-12-14 15:30
just part of it, sometimes it was even hard to notice with the drawn bboxes

**Comment by fmassa** [comment] 2018-12-14 16:45
Interesting. I'm not yet sure where/why this would crash in the current code, I'd need to check a bit more.

**Comment by txytju** [comment] 2018-12-16 07:53
I have also met the problem and I'm sure all the images in my dataset have bboxes. I' tring to remove out-of-image-boundary bbox annotations and find out will that works.

**Comment by fmassa** [comment] 2018-12-17 10:37
@txytju let us know if that was what was necessary to fix your problem

**Comment by rodrigoberriel** [comment] 2019-01-30 15:33
@fmassa In my case, the problem was caused by some bounding boxes with `width` or `height` between `[0, 1]` (COCO dataset<sup>1</sup>). These are only removed after `.clip_to_image(...)`. The problem arises at [`bounding_box.py#L85-L86`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/structures/bounding_box.py#L85-L86), where `({w,h} - TO_REMOVE).clamp(min=0)` sets `xmin==xmax` and/or `ymin==ymax` when the width and/or height of the bboxes are less than or equal to `TO_REMOVE=1`. The problem is that, later, [`clip_to_image(...)`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/structures/bounding_box.py#L214-L224) checks `(box[:, 3] > box[:, 1]) & (box[:, 2] > box[:, 0])`, which becomes `False` in these cases.

My workaround was to add an extra check in the `if remove_images_without_annotations`, anticipating these cases. This is what I did (I added some prints because I always want to be aware of this fact):

```python
# filter images without detection annotations
if remove_images_without_annotations:
    total_removed = 0
    len_ids_before = len(self.ids)
    self.ids = [
        img_id
        for img_id in self.ids
        if len(self.coco.getAnnIds(imgIds=img_id, iscrowd=None)) > 0
    ]
    total_removed += len_ids_before - len(self.ids)
    if total_removed > 0:
        print("{} images were removed because they do not have annotations!".format(total_removed))

    ids_to_remove = []
    for img_id in self.ids:
        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anno = self.coco.loadAnns(ann_ids)
        anno = [obj for obj in anno if obj["iscrowd"] == 0]
        boxes = [obj["bbox"] for obj in anno]
        boxes = torch.as_tensor(boxes).reshape(-1, 4)  # guard against no boxes
        img_data = self.coco.loadImgs(img_id)[0]
        img_size = (img_data['width'], img_data['height'])  # try to speed up by avoid loading the image
        target = BoxList(boxes, img_size, mode="xywh").convert("xyxy")
        target = target.clip_to_image(remove_empty=True)
        if len(target) == 0:
            ids_to_remove.append(img_id)

    total_removed += len(ids_to_remove)
    if len(ids_to_remove) > 0:
        self.ids = [img_id for img_id in self.ids if img_id not in ids_to_remove]
        print("These {} images were removed after `clip_to_image`: {}".format(
            len(ids_to_remove), ', '.join(list(map(str, ids_to_remove)))
        ))

    if total_removed > 0:
        print('In total, {} images without annotations were removed'.format(total_removed))
```

If you prefer the [current exception-oriented](https://github.com/facebookresearch/maskrcnn-benchmark/pull/37) approach, one exception could be thrown [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/structures/bounding_box.py#L220-L223):

```python
if remove_empty:
    box = self.bbox
    keep = (box[:, 3] > box[:, 1]) & (box[:, 2] > box[:, 0])
    if keep.sum() == 0:
        raise ValueError("No valid ground-truth boxes available for one of the images")
    return self[keep]
```

I can submit a PR if you tell me which one is the preferred solution (if any). I personally prefer the first (maybe you know a better/faster way to check this).

In case you need:
- Python 3.5
- `torch.__version__`: 1.0.0.dev20190125
- `git log -n 1`: 5f2a8263

<sup><sup>1</sup>There are 29 of these cases in the COCO2014 train dataset itself, but there are other bboxes in these images. The error happened to me because I was using a subset of the classes, which led these other bboxes to be discarded.</sup>

**Comment by fmassa** [comment] 2019-01-31 10:14
Hi @rodrigoberriel 

Wow, that's some pretty nice investigation!

If the underlying reason is that we have annotations with `width` or `height` < 1 (which is probably annotation error btw), then I think I'd prefer the first approach where we remove those images beforehand.

But I think there is a slightly simpler way of implementing it: why not just `loadAnns`, and then remove the image if a condition like
```python
if all(any(o < 1 for o in obj["bbox"][2:]) for obj in anno if obj["iscrowd"] == 0):
    to_remove.append(img_id)
```
applies for image `img_id`?

If you could send such a PR it would be awesome!

**Comment by rodrigoberriel** [comment] 2019-01-31 14:00
@fmassa I've just submitted the PR with small modifications: just changed your suggestion to less than or **equal to**, removed the prints (I can bring them back using the logger, but it did not feel correct -- logger is not used in the class), and formatted the code using black.

**Comment by fmassa** [comment] 2019-01-31 15:51
I've merged https://github.com/facebookresearch/maskrcnn-benchmark/pull/396
@rodrigoberriel do you think we could close this issue?

**Comment by fmassa** [comment] 2019-01-31 19:32
Closing per @rodrigoberriel comment. Please if you still face similar issues just let us know

**Closed by fmassa** 2019-01-31 19:32 UTC
Labels: awaiting response
