### ISSUE TITLE
How Can I quarentee that the object mask will not cross the real boundries object?

### ISSUE THREAD

**Issue by jediofgever** [facebookresearch/maskrcnn-benchmark#412] opened 2019-02-09 06:59 UTC
## ❓ Questions and Help

Hi,
I would to know if the question in title can be achieved. In my application I should quarentee that the mask wont cross real boundries of object, it is ok if some part of the object is not being covered by mask. 

Do you have any suggestions to get there ? 

Thank you for your help

**Comment by fmassa** [comment] 2019-02-11 09:51
Hi,

I'm not sure that we can guarantee that the masks won't cross the boundaries of the object: if we knew the boundaries then we would have the masks right away.

You could apply some erosion on the masks to make them smaller, but that wouldn't guarantee that the problem is fixed.

I'm closing the issue, but let me know if you have further questions.

**Closed by fmassa** 2019-02-11 09:51 UTC
