### ISSUE TITLE
ImportError: ../maskrcnn_benchmark/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2at15UndefinedTensor10_singletonE

### ISSUE THREAD

**Issue by ypxie** [facebookresearch/maskrcnn-benchmark#226] opened 2018-11-29 02:13 UTC
## ❓ Questions and Help
pytorch 1.0
CUDA 9.0
PYTHON 3.5
Ubuntu 16.04

**Comment by fmassa** [comment] 2018-11-29 10:44
This is a duplicate of https://github.com/facebookresearch/maskrcnn-benchmark/issues/119
You are probably not using PyTorch 1.0, and there is an old PyTorch version laying around in your machine that is conflicting.
Try doing in your interpreter
```python
import torch
print(torch.__version__)
```
and it will probably show that you are not using 1.0

**Closed by fmassa** 2018-11-29 10:44 UTC

**Comment by Dandi007** [comment] 2018-12-14 08:47
I have the same issue too.
cuda 9.2
pytorch-nightly           1.0.0.dev20181211 py3.7_cuda9.0.176_cudnn7.4.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

when I do print torch.__version__,it outpus 1.0.0 so my torch version is correct.

but I still got this issue.

**Comment by Dandi007** [comment] 2018-12-14 08:50
this is my env info

Collecting environment information...
PyTorch version: 1.0.0.dev20181211
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 17.10
GCC version: (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
CMake version: version 3.9.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2018.0.3                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.4            py37h4414c95_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.0.1            py37h4414c95_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch-nightly           1.0.0.dev20181211 py3.7_cuda9.0.176_cudnn7.4.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.2.1                     <pip>

**Comment by Dandi007** [comment] 2018-12-14 08:53
I can run web.py successfully，
python webcam.py --min-image-size 800

but when I run nms.py,I got
ImportError: /media/disk1/PycharmProjects/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by fmassa** [comment] 2018-12-14 09:55
what is `nms.py`?

**Comment by Dandi007** [comment] 2018-12-17 09:48
I just run it to run this line of code:

# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
# from ._utils import _C
from maskrcnn_benchmark import _C

nms = _C.nms
# nms.__doc__ = """
# This function performs Non-maximum suppresion"""

it raise error when trying to import _C

**Comment by fmassa** [comment] 2018-12-17 10:08
This means that `maskrcnn-benchmark` was not properly installed.

Can you try `rm -rf build/` from `maskrcnn-benchmark` folder, and try installing it again according to the instructions in `INSTALL.md`?

**Comment by niaoyu** [comment] 2019-01-08 08:21
> This means that `maskrcnn-benchmark` was not properly installed.
> 
> Can you try `rm -rf build/` from `maskrcnn-benchmark` folder, and try installing it again according to the instructions in `INSTALL.md`?

Oh... Forget to delete all the files. It works for me

**Comment by qushan326** [comment] 2019-03-20 07:07
![image](https://user-images.githubusercontent.com/38337760/54665151-264b8c00-4b21-11e9-9372-35ecb4f0f2c0.png)

actually this maybe not some wrong with installation, as it's said in pytorch's tutorial:
https://pytorch.org/tutorials/advanced/cpp_extension.html
![image](https://user-images.githubusercontent.com/38337760/54665345-cacdce00-4b21-11e9-8e6d-a434bfe8d1f7.png)

**Comment by sdw95927** [comment] 2019-05-03 23:38
Usually reinstalling packages and some important depencencies (e.g. gcc) solves most of the problems lol

**Comment by futureisatyourhand** [comment] 2019-06-02 01:55
conda install -c pytorch pytorch-nightly torchvision cudatoolkit=10.0
 issue:
from maskrcnn_benchmark import _C ImportError: maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
or from torchvision import _C.
 this do run by:
    conda uninstall pytorch
    conda uninstall pytorch-nightly
    conda uninstall torch
    codna uninstall torchvision
 then:
    conda install -c pytorch pytorch-nightly torchvision cudatoolkit=10.0
    pip install torchvision==0.2.2
 successfully!!

**Comment by i-chaochen** [comment] 2019-06-04 16:17
> conda install -c pytorch pytorch-nightly torchvision cudatoolkit=10.0
> issue:
> from maskrcnn_benchmark import _C ImportError: maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
> or from torchvision import _C.
> this do run by:
> conda uninstall pytorch
> conda uninstall pytorch-nightly
> conda uninstall torch
> codna uninstall torchvision
> then:
> conda install -c pytorch pytorch-nightly torchvision cudatoolkit=10.0
> pip install torchvision==0.2.2
> successfully!!

how do you success with cuda 10.0? 
I tried python webcam.py --min-image-size 800

and I got 
ImportError: libcudart.so.9.0 cannot open shared object file no such file or directory

**Comment by futureisatyourhand** [comment] 2019-06-05 13:20
the version of cuda on my server is 10.0, if  you use cuda9.0, I suggest you try cuda9.2, the version can run well, since I found cuda9.0 often doesn't work very well.

**Comment by futureisatyourhand** [comment] 2019-06-05 13:22
the version of cuda on my server is 10.0, if you use cuda9.0, I suggest you try cuda9.2, the version can run well, since I find cuda9.0 often doesn't work very well.

**Comment by i-chaochen** [comment] 2019-06-10 13:47
> the version of cuda on my server is 10.0, if you use cuda9.0, I suggest you try cuda9.2, the version can run well, since I find cuda9.0 often doesn't work very well.

My machine is cuda 10.0 as well, but when I followed your steps uninstall everything and conda install again.

I met the cuda library problem. Does it mean I need to uninstall cuda10.0 and reinstall cuda9.2? 
ImportError: libcudart.so.9.0 cannot open shared object file: No such file or directory

**Comment by milkytipo** [comment] 2019-06-17 02:11
> > the version of cuda on my server is 10.0, if you use cuda9.0, I suggest you try cuda9.2, the version can run well, since I find cuda9.0 often doesn't work very well.
> 
> My machine is cuda 10.0 as well, but when I followed your steps uninstall everything and conda install again.
> 
> I met the cuda library problem. Does it mean I need to uninstall cuda10.0 and reinstall cuda9.2?
> ImportError: libcudart.so.9.0 cannot open shared object file: No such file or directory

you just need to reinstall it again as the instruction, I met the the same problem and reinstall it, it worked now

**Comment by milkytipo** [comment] 2019-06-17 02:12
> My machine is cuda 10.0 as well, but when I followed your steps uninstall everything and conda install again.
> I met the cuda library problem. Does it mean I need to uninstall cuda10.0 and reinstall cuda9.2?
> ImportError: libcudart.so.9.0 cannot open shared object file: No such file or directory
you just need to reinstall it again as the instruction, I met the the same problem and reinstall it, it worked now

**Comment by milkytipo** [comment] 2019-06-17 02:12
> My machine is cuda 10.0 as well, but when I followed your steps uninstall everything and conda install again.
> 

> I met the cuda library problem. Does it mean I need to uninstall cuda10.0 and reinstall cuda9.2?
> ImportError: libcudart.so.9.0 cannot open shared object file: No such file or directory

you just need to reinstall it again as the instruction, I met the the same problem and reinstall it, it worked now

**Comment by futureisatyourhand** [comment] 2019-06-17 02:19
> > the version of cuda on my server is 10.0, if you use cuda9.0, I suggest you try cuda9.2, the version can run well, since I find cuda9.0 often doesn't work very well.
> 
> My machine is cuda 10.0 as well, but when I followed your steps uninstall everything and conda install again.
> 
> I met the cuda library problem. Does it mean I need to uninstall cuda10.0 and reinstall cuda9.2?
> ImportError: libcudart.so.9.0 cannot open shared object file: No such file or directory

you can try to  reinstall "conda install -c pytorch pytorch-nightly torchvision cudatoolkit=9.2" or reinstall by my instruction.

**Comment by zimenglan-sysu-512** [comment] 2019-08-01 02:45
hi @fmassa 
it seems that torch_nightly-1.2.0 is not compatible with torchvision-0.3
