### ISSUE TITLE
url issue: KeyError: 'content-length'

### ISSUE THREAD

**Issue by JSharp4273** [facebookresearch/maskrcnn-benchmark#321] opened 2019-01-05 00:51 UTC
## ❓ Questions and Help

Hello 

I am trying to run the demo: **Mask_R-CNN_demo.ipynb**
Untill now each time I try to run the file I receive this error: **KeyError: 'content-length'**

This error come from the file **predictor.py** that call a function from **model_zoo.py** 
At line 73 of the later file: _file_size = int(u.headers["Content-Length"])_ the attribue _header_ is a data structure that in its member __store_ does not have any key named: "Content-Length".

Any help is appreciate.

**Comment by fmassa** [comment] 2019-01-07 14:08
Hi,

What's the path of the file that the code is trying to download?
Note that the old links that we have were replaced 17 days ago in https://github.com/facebookresearch/maskrcnn-benchmark/pull/301, so you should use the newer version instead.

**Comment by JSharp4273** [comment] 2019-01-07 19:53
It is not something "I" try to download it the algorithm who do it automaticaly.
It tries to connect to this url:
https://s3-us-west-2.amazonaws.com/detectron/35858933/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl

But another time I am just trying to execute the demo as is **except some print I did not apply any modifications to the demo nor to any files**.

**Comment by fmassa** [comment] 2019-01-08 09:46
Can you try updating your copy of `maskrcnn-benchmark`? As I mentioned before, in https://github.com/facebookresearch/maskrcnn-benchmark/pull/301/files I changed the URLs to point to the new location.
This should fix your problem.

I'm closing this issue as I believe the problem is fixed in the latest version, but feel free to comment if it's not working for you even after updating `maskrcnn-benchmark`.

**Closed by fmassa** 2019-01-08 09:46 UTC
Labels: awaiting response

**Comment by JSharp4273** [comment] 2019-01-08 21:21
It fix the issue ... but another one has come:

**UnpicklingError: pickle data was truncated**
