### ISSUE TITLE
Convert binary mask to polygon

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/maskrcnn-benchmark#381] opened 2019-01-24 14:28 UTC
## ❓ Questions and Help

Is there a function that allows me to convert binary masks to polygons? this would help in training the model on new datasets that come with polygons like COCO.

Thanks!

**Comment by fmassa** [comment] 2019-01-24 14:32
Hi,

I don't think it would be that easy to get a reasonable to convert binary masks to polygon.
It might be simpler to try out using support for binary masks as discussed in https://github.com/facebookresearch/maskrcnn-benchmark/issues/256

They seem to have managed to make it work with a few changes to #150 

I'm closing this issue as I think it's in this case better to have straight support for binary masks, but let me know if you think otherwise.

**Closed by fmassa** 2019-01-24 14:32 UTC

**Comment by IssamLaradji** [comment] 2019-01-24 14:41
Thanks for the reply. 
Aren't polygons and RLE less expensive to operate on than binary masks? I think the `pycocotools` evaluation expects polygons/rle to compute the AP scores, right?

**Comment by IssamLaradji** [comment] 2019-01-24 14:47
Lines 132-151 in https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py show that the binary masks are converted to `RLE` for evaluation. It seems that the `pycocotools` has much better support for rle than polygons as the `encode` and `decode` functions seamlessly convert the binary mask to rle format and vice versa.

**Comment by fmassa** [comment] 2019-01-24 14:49
@IssamLaradji the problem is that performing any operations on RLE is very complicated, and the easiest approach is to simply convert to a binary mask, apply the transformation and convert back to RLE.

Thus, speed-wise I don't think it would be relevant to support RLE except if we spend some significant efforts writing methods that operate directly on RLE.

**Comment by IssamLaradji** [comment] 2019-01-24 14:58
@fmassa makes sense!

**Comment by txytju** [comment] 2019-02-06 09:12
> Thanks for the reply.
> Aren't polygons and RLE less expensive to operate on than binary masks (unless it's sparse binary mask)? I think the `pycocotools` evaluation expects polygons/rle to compute the AP scores, right?

@IssamLaradji In my case, instance masks may have holes, so you can not use polygons and binary mask is the only way. And binary mask do use more GPU memory.
