### ISSUE TITLE
Can this implementation handle images without objects?

### ISSUE THREAD

**Issue by SingL3** [facebookresearch/maskrcnn-benchmark#192] opened 2018-11-21 07:03 UTC
Hello!
I want to train a model with some samples that has no objects ( just background ).
Can this implementation handle that?

**Comment by fmassa** [comment] 2018-11-21 10:12
Hi,

This is a duplicate of https://github.com/facebookresearch/maskrcnn-benchmark/issues/169

Let's keep the discussion there.

**Closed by fmassa** 2018-11-21 10:12 UTC
